query getCustomer($customerAccessToken: String!){
    customer(customerAccessToken: $customerAccessToken){
        id
        lastName
        firstName
        email
        defaultAddress{
            address1
            address2
            city
            company
            country
            firstName
            lastName
            name
            zip
            provinceCode
            province
            phone
            id
        }
    }
}
