query getProduct($productId: ID!){
    node(id: $productId) {
        ... on Product {
            variants(first: 1) {
                edges {
                    node {
                        id
                    }
                }
            }
        }
    }
}
